# Generated by Django 2.0.6 on 2018-06-12 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, verbose_name='등록일')),
                ('file_key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file_path', models.FileField(upload_to=file.models.get_upload_path)),
                ('expire_min', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
