# Generated by Django 2.0.6 on 2018-06-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20180626_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_unique_key',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
