# Generated by Django 2.0.6 on 2018-06-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20180629_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_unique_key',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_key',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
