# Generated by Django 2.0.6 on 2018-06-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20180629_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
