# Generated by Django 2.0.6 on 2018-06-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('account', '0002_remove_user_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.Project', verbose_name='project_key'),
            preserve_default=False,
        ),
    ]
