# Generated by Django 2.0.6 on 2018-06-23 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180612_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=170),
            preserve_default=False,
        ),
    ]
