# Generated by Django 2.0.6 on 2018-06-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180623_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_key',
            field=models.CharField(default='', max_length=170, unique=True),
        ),
    ]
