# Generated by Django 2.0.6 on 2018-08-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180626_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='variables',
            field=models.TextField(max_length=8000),
        ),
    ]
