# Generated by Django 2.0.6 on 2018-06-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=30)),
                ('project_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('global_variables', models.TextField(max_length=4000)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
